services:
  mysql:
    image: mysql:8.3
    container_name: db-1
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./hive.sql:/docker-entrypoint-initdb.d/hive.sql
    restart: unless-stopped
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: web-1
    env_file:
      - .env
    ports:
      - 3000:3000
    restart: unless-stopped
  ai:
    build: ./ai/
    command: flask --app app run --debug
    ports:
      - "3030:3030"
    volumes:
      - ./ai/itvb23ows-hive-ai:/ai/itvb23ows-hive-ai/ai-1
volumes:
  db-data: