services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./itvb23ows-starter-code:/itvb23ows-starter-code/web-1/src
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: hive
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ROOT_USER: root
    volumes:
      - ./hive.sql:/hive.sql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password', '--init-file=/hive.sql']
volumes:
  db-data: